/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */
package front;

import back.Graph;
import back.PointEuclidien;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author donat
 */
public class AskForCreatingRandomPointSet extends javax.swing.JDialog {

    /**
     * Creates new form AskForCreatingRandomPointSet
     */
    public AskForCreatingRandomPointSet(java.awt.Frame parent) {
        super(parent, true);
        initComponents();
        xMinSpinner.setModel(new SpinnerNumberModel(0, -100, 100, 1));
        yMinSpinner.setModel(new SpinnerNumberModel(0, -100, 100, 1));
        xMaxSpinner.setModel(new SpinnerNumberModel(50, -100, 100, 1));
        yMaxSpinner.setModel(new SpinnerNumberModel(50, -100, 100, 1));
        nbPointSpinner.setModel(new SpinnerNumberModel(20, 2, 50, 1));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        nbPointLabel = new javax.swing.JLabel();
        xLabel = new javax.swing.JLabel();
        yLabel = new javax.swing.JLabel();
        okButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        yMinSpinner = new javax.swing.JSpinner();
        xMaxSpinner = new javax.swing.JSpinner();
        nbPointSpinner = new javax.swing.JSpinner();
        xMinSpinner = new javax.swing.JSpinner();
        yMaxSpinner = new javax.swing.JSpinner();
        xMinLabel = new javax.swing.JLabel();
        xMaxLabel = new javax.swing.JLabel();
        yMaxLabel = new javax.swing.JLabel();
        yMinLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        nbPointLabel.setText("Nombre de points");

        xLabel.setText("X");

        yLabel.setText("Y");

        okButton.setText("OK");
        okButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                okButtonActionPerformed(evt);
            }
        });

        cancelButton.setText("Annuler");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });

        yMinSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yMinSpinnerStateChanged(evt);
            }
        });

        xMaxSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xMaxSpinnerStateChanged(evt);
            }
        });

        xMinSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                xMinSpinnerStateChanged(evt);
            }
        });

        yMaxSpinner.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                yMaxSpinnerStateChanged(evt);
            }
        });

        xMinLabel.setText("Min.");

        xMaxLabel.setText("Max.");

        yMaxLabel.setText("Max.");

        yMinLabel.setText("Min.");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(nbPointLabel)
                        .addGap(18, 18, 18)
                        .addComponent(nbPointSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(yMinLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(yMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(xLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(xMinLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(xMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 29, Short.MAX_VALUE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(okButton)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(yMaxLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 34, Short.MAX_VALUE)
                                        .addComponent(yMaxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(xMaxLabel)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(xMaxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(cancelButton)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap(63, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nbPointLabel)
                    .addComponent(nbPointSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(xLabel)
                    .addComponent(xMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xMaxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xMinLabel)
                    .addComponent(xMaxLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(yMinSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yMaxSpinner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(yMaxLabel)
                    .addComponent(yMinLabel)
                    .addComponent(yLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(okButton)
                    .addComponent(cancelButton))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void okButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_okButtonActionPerformed
        this.OK = true;
        this.dispose();
    }//GEN-LAST:event_okButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void xMinSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xMinSpinnerStateChanged
        ((SpinnerNumberModel) xMaxSpinner.getModel()).setMinimum((int) xMinSpinner.getValue());
        xMaxSpinner.setValue(Math.max((int) xMaxSpinner.getValue(), (int) xMinSpinner.getValue()));
    }//GEN-LAST:event_xMinSpinnerStateChanged

    private void xMaxSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_xMaxSpinnerStateChanged
        ((SpinnerNumberModel) xMinSpinner.getModel()).setMaximum((int) xMaxSpinner.getValue());
        xMinSpinner.setValue(Math.min((int) xMaxSpinner.getValue(), (int) xMinSpinner.getValue()));
    }//GEN-LAST:event_xMaxSpinnerStateChanged

    private void yMinSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yMinSpinnerStateChanged
        ((SpinnerNumberModel) yMaxSpinner.getModel()).setMinimum((int) yMinSpinner.getValue());
        yMaxSpinner.setValue(Math.max((int) yMaxSpinner.getValue(), (int) yMinSpinner.getValue()));

    }//GEN-LAST:event_yMinSpinnerStateChanged

    private void yMaxSpinnerStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_yMaxSpinnerStateChanged
        ((SpinnerNumberModel) yMinSpinner.getModel()).setMaximum((int) yMaxSpinner.getValue());
        yMinSpinner.setValue(Math.min((int) yMaxSpinner.getValue(), (int) yMinSpinner.getValue()));

    }//GEN-LAST:event_yMaxSpinnerStateChanged

    public boolean OK() {
        return this.OK;
    }

    public Graph<PointEuclidien> getGeneratedGraph() {
        return Graph.randomPointSet((int) nbPointSpinner.getValue(), 
                ((Number) xMinSpinner.getValue()).doubleValue(),
                ((Number) xMaxSpinner.getValue()).doubleValue(),
                ((Number) yMinSpinner.getValue()).doubleValue(),
                ((Number) yMaxSpinner.getValue()).doubleValue());
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel nbPointLabel;
    private javax.swing.JSpinner nbPointSpinner;
    private javax.swing.JButton okButton;
    private javax.swing.JLabel xLabel;
    private javax.swing.JLabel xMaxLabel;
    private javax.swing.JSpinner xMaxSpinner;
    private javax.swing.JLabel xMinLabel;
    private javax.swing.JSpinner xMinSpinner;
    private javax.swing.JLabel yLabel;
    private javax.swing.JLabel yMaxLabel;
    private javax.swing.JSpinner yMaxSpinner;
    private javax.swing.JLabel yMinLabel;
    private javax.swing.JSpinner yMinSpinner;
    // End of variables declaration//GEN-END:variables
    private boolean OK = false;
}
